### PR TITLE
Code clean-ups

### PR DESCRIPTION
**Pull request by csnover**
Since I had to pull binread into my tree to fix the field-level asserts, I ended up getting a bunch of warnings from rustc and clippy, so I went through and fixed them. Each kind of fix exists within a separate commit just in case you don’t want to include some of them.

### CODE REVIEW

**Comment by jam1garner** [comment]
So all of this looks good, however would you mind taking out the commits for "remove array size 0 impl" and removing the doc comment for the tuple generation?

The base case for the tuple one is used for the unit type impl iirc, so yes it's 0 to 20, which is why I feel the doc comment is needed.

Anyways as for the array size zero: I prefer the consistency, I see no real harm in its existence, and would be a breaking change to remove.

**Comment by csnover** [comment]
> The base case for the tuple one is used for the unit type impl iirc, so yes it's 0 to 20, which is why I feel the doc comment is needed.

It’s not accurate though since the macro invocation goes up to 32, not 20. Perhaps a better comment would simply note that the macro also generates the unit type implicitly by recursion? I actually didn’t pay enough attention to realise that was happening, I only saw the invocation was from b1 to b32, so if the comment’s intent is to point out the unit type generation it managed to go over my dumb head :-).

Further: the unit type implementation just happens to be in the zero-argument match and generates a totally different implementation than the rest. It seems to me that the whole code would be clearer by moving the unit type implementation out of the macro entirely.

All said, I’m not actually sure that it makes sense to have a unit type implementation since it seems to me like that would just be a bug in consumer code (see below, since the same thought applies to the zero-length array case).

> Anyways as for the array size zero: I prefer the consistency, I see no real harm in its existence, and would be a breaking change to remove.

The harms are marginal, but they are there. One is that Clippy warns that the inner loop is not doing anything in this case, so that warning would need to be suppressed. The other one is that trying to use binread on a zero-size array is probably a bug since it doesn’t make sense. Dropping the implementation would generate a compile-time error instead of silently just not reading anything. I acknowledge the breaking nature of the change and that is definitely a strong consideration for not changing it, but I don’t know why someone would’ve ever used this impl intentionally; can you think of a reason why it would be intentional and valid to do so? I suppose when const generics land it’ll be a moot point since it’ll just be a single implementation over `N` but I am genuinely curious if you know of a valid use case here.

Let me know your thoughts. Thanks!

**Comment by jam1garner** [comment]
My main argument in favor of handling the 0 case is for those who already have a fake const generics implementation (like the LengthAtMost32 in the standard library) who want to blanket impl for some helper type. If their fake const generics is implanted for 32 it wouldn't be able to blanket impl. While yes, 0 items is sometimes useless or a bug (I understand that more for the unit type tbh, but I guess it's sometimes possible to typo an empty array), it's also helpful to have a no-op type available imo (and I think the unit type fits that best). I know these are really minor reasons to allow for a possible bug class but imo the burden of necessity is on the choice of special casing, which in this case, is your suggestion. I find "this is likely a bug because it's a no-op" is kinda a weak reason to both special case and be a breaking change unfortunately. I can totally see where you're coming from and appreciate your view on it but it feels like poking the bees nest to remove. I would accept moving the unit type to be outside the macro though, since you mentioned that.

Also as for 20 in the comment vs 32—that's totally my bad. Originally it was 20! I upped it to 32 to match the standard library but forgot to update the comment.

**Comment by csnover** [comment]
Thanks for the thoughtful discussion. I have spent a lot of my career working on development tools, so I have a very defensive posture when it comes to any place where a bug might accidentally happen. :-) I’ve replaced the array/tuple commits with new ones which retain the zero-size impls and change the way array values are assigned to avoid the zero range loop. I moved the unit type implementation out of the tuple macro and changed the comment to be evergreen. Let me know if you see anything else you would like changed.

**Comment by jam1garner** [comment]
Oh trust me I totally get where you're coming from, I certainly appreciate the attempt at minimum! Looks all good to me now, I'll try to get a release out soon.

**Pull request merged**
