### PR TITLE
So I accidentally rewrote most of binread_derive and fixed a bunch of bugs

### LINKED ISSUE #35: Magic attr does not apply to enum inner fields
It seems that currently the magic attr is not respected on fields inside enums. Not sure if this was ever a consideration, but it would be super neat to have for assert convenience in nested structures.

On `1.4.1` the test `with_magic` here fails for me:

```rust

#[cfg(test)]
mod tests {
    use binread::{io::cursor::Cursor, BinRead, BinReaderExt};

    #[test]
    fn without_magic() {
        let mut cursor = Cursor::new(b"ABCD");

        #[derive(PartialEq, Debug, BinRead)]
        enum WithoutMagic {
            #[br(magic(b"A"))]
            Inner { b: u8, c: u8, d: u8 },
        }

        let without_magic: WithoutMagic = cursor.read_le().unwrap();
        assert_eq!(
            WithoutMagic::Inner {
                b: b'B',
                c: b'C',
                d: b'D',
            },
            without_magic
        );
    }

    #[test]
    fn with_magic() {
        let mut cursor = Cursor::new(b"ABCD");

        #[derive(PartialEq, Debug, BinRead)]
        enum WithMagic {
            #[br(magic(b"A"))]
            Inner {
                b: u8,
                #[br(magic(b"C"))]
                d: u8,
            },
        }

        let with_magic: WithMagic = cursor.read_le().unwrap();
        assert_eq!(WithMagic::Inner { b: b'B', d: b'D' }, with_magic);
    }
}
```

### PR DESCRIPTION
**Pull request by csnover**
Hi.

Once upon a time, on a dark and stormy night, I needed to read binary data. I looked at a bunch of crates and BinRead did the most of what I needed, which was great!, but there were some features which were missing, and I was often frustrated by error reporting which pointed unhelpfully to `#[derive(BinRead)]` instead of where I’d made my dumb mistakes. This was less great.

I went to try to improve some of the error reporting and add the features I wanted, and had trouble really understanding the code flow of the derive macro, because I am not a smart person and I couldn’t quite track where things were happening or see how to add stuff without it feeling like a questionable hack. (Only I am allowed to be a questionable hack.)

So I started trying to untangle everything, and, er, ended up rewriting most of the proc-macro.

As a maintainer, I know I would not really appreciate getting a gigantic pull request dumped in my lap like this, so I’m very sorry about doing this, and it is 100% my fault for not finding a better way to deliver these changes in smaller chunks. At one point the changes actually ended up deleting more code than they added, but then I added a bunch of tests, and then I found a bunch of edge cases needing fixing, and that was the end of that good feeling.

I tried to avoid making many backward-incompatible changes so migration should be very easy (I didn’t have to make any changes to my own code, and only one change I can think of to make an existing test case continue to work), but there are a few of them, so the major version number is bumped in this PR.

Architecturally, the repository has been changed to use workspaces instead of having two separate repos, because trying to maintain code with interdependent tests across two repos is literally impossible. This is where a fair amount of “new” code is actually coming from.

The proc-macro side is now split into a parser half and a code generation half. The parser half is responsible for converting `syn::DeriveInput` into a tree of objects that contains the properties that the code generator needs, and for validating the input. This lets the code generation side be all infallible code. This should hopefully make implementing other features in the future much easier too, since parsing is no longer mixed in with code generation. (It did make it easy enough that I could confidently fix #35 in under 10 minutes and without duplicating any code.)

Changed stuff includes:

* Much code deduplication, elimination of unnecessary heap allocations, etc. Hopefully the proc-macro runs a bit faster now—at one point during performance optimising I observed ~10% speed-up, though my laptop has awful thermals so it is hard to get totally reliable benchmarks.
* Added a `try_map` directive, which is like `map` except fallible.
* The `if` directive now works for any field, not just `Option` fields, and optionally accepts a computed value when the condition is false.
* Derive will now emit all parse-time errors, not just the first one it encounters, so authors don’t have to run multiple fix-recompile cycles to make their code work.
* There are now tests for everything, guided by code coverage analysis. Every possible code path, including error paths, is exercised at least once, so there should be fewer bugs and unknown edge conditions (though I am sure some still exist since grcov is a little broken on my machine).
* The things which go inside `#[br]` attributes are renamed “directive” in docs to try to avoid confusion about whether “attribute” refers to a Rust attribute or a BinRead attribute. Now one of them is unambiguously “attribute” and the other is unambiguously “directive”.
* Invalid combinations of directives in attributes now trigger errors instead of undefined behaviour or no behaviour. Directives which are not valid in a given position are no longer silently accepted. It is a bit hard to enumerate all of these strictness changes, but at least:
  * `pre_assert` works where it didn’t before when matching unit-like enums.
  * `assert` on an enum actually does something (though I don’t know how useful its new behaviour is—it applies the assertion to every variant so any referenced field name must exist in all of the variants).
  * `deref_now` and `offset_after` are now mutually exclusive.
  * `calc`, `default`, `ignore`, and `parse_with` are now mutually exclusive.
  * Impossible magic types like `bool`, `&str`, and verbatim, which AFAICT never worked, are (at least temporarily) disallowed.
* Errors parsing a directive are now accurately reported instead of claiming that the keyword is invalid.
* The reader should no longer be left in an undefined state if a derived object fails to parse. When this happens, the reader should seek back to its original position.
* Map and custom parse functions can now be generated functions, instead of being restricted to being a closure or path.
* `assert`, when passed a string literal as the second argument, will return an `AssertFail` error instead of a `Custom` error.
* When a string literal is used as the second argument to `assert`, it will be treated as a format string and extra arguments will be passed in, just like the standard `assert!` macro.
* `ignore` is now *actually* an alias for `default`, per the documentation. Previously it literally just didn’t do anything which meant the only way `ignore` could be used would be if you also `import` a variable with the same name. The equivalent to the old behaviour can be done using `calc(import_var)` instead.
* `binread` crate is now compliant with `rust_2018_idioms` and `binread_derive` is compliant with `rust_2018_idioms` and `clippy::pedantic`.
* The `pos` field of errors is now properly a `u64` instead of a possibly silently truncating `usize`. (#29)
* Issue #26 is fixed.
* Issue #35 is fixed.
* no_std compilation is fixed.
* The position given in assertion failures is now correct. Previously it was pointing to the byte *after* the field.
* Undocumented `import_tuple` and `args_tuple` are now documented.
* `return_unexpected_error` is now documented and should works as desired.
* `offset_after` is now fully documented.
* Errors in map functions and other expressions no longer point to `#[derive(BinRead)]`.
* Magic enums with only some variants with magic, or where magic is not on the first variant, now work properly.
* Unnecessary private no-op functions were removed, and a `__private` module added, so that private APIs used by derived code are not exposed in a way that would ever suggest to users to try to use them. I kept the old broken `error::assert` function around with a deprecated attribute because it hadn’t been annotated with `#[doc(hidden)]`.

There are probably some other things, too, but I think I hit all the significant points in this list. To get an idea of the workflow now for new features, you can try looking at the blurb I wrote in binread_derive/README.md to help others get started quickly.

One breaking change I wanted to make but didn’t (in order to keep upgrades simple) was to change the `self_<index>` variables used by tuple structs to just `_<index>` since that’s the convention I’ve seen in every other proc-macro I’ve used that has to interact with tuple fields.

I did almost no work on the runtime library side, just enough to fix no_std and change whatever support code was needed by the derive and to add tests.

OK, so this is already too many words, just like this PR is too many code changes. Sorry, again. Really. Everything is definitely not perfect with this refactored design, but I feel like it is enough of an improvement that it is worth trying to push upstream. I know that the plan was to go to `binrw`, but since that doesn’t really seem to have moved at all, this is hopefully at least a better baseline for whatever future work is planned to add write-support. I’ll need to write stuff eventually too so I’ll try to be more communicative if I ever find that I need to start adding that support myself.

Thanks for reading. I hope to never do this to you again. :-)

### CODE REVIEW

**Comment by csnover** [comment]
Because I am a bad person who cannot stop touching things, I just added one more commit to extend how the `if` directive works so that it can be used generically on any type, not just `Option` types. I’ve updated the list of changes in the PR description with this extra.

**Comment by jam1garner** [comment]
oh god

**Comment by jam1garner** [comment]
To be clear I am 100% meaning to review this soon. Thank you very much for all the work you've done!

**Comment by csnover** [comment]
Thank you for the positive comment and the extra information on your plan to review. I may have deserved that first one, but it did come across more negatively than you probably intended.

Let me know if you have an idea about something I can do to help ease the review process. I moved to a monorepo at the beginning of the changeset so if you diff [from that commit](https://github.com/csnover/binread/compare/5e362dc717588db279699e28ed6d4293632c3221..split-parser) that should give a clearer overview.

A fairly substantial chunk of ‘new’ code is just tests, so it’s not quite as bad as it looks from the raw stats. I also went through a few iterations before arriving at the final design, and those are represented in the commit history even though they are not part of the final code since I didn’t want to squash everything and ruin blames/bisects.

I’ve pushed one more change just now since I wrote a bad test for the `try_map` feature so it was not working correctly when applied at the top-level. That should hopefully be it for this changeset, modulo any changes you want to see, unless I run into any other mistakes as I continue to use this patched version in my own code.

I have some other small patches in the pipeline, but will open separate, normal-sized PRs after/if this lands.

Thanks again!

**Pull request merged**
